development:
  adapter: postgresql
  encoding: unicode
  database: todo_development
  pool: 5
  username: nblanchet
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: todo_development
  pool: 5
  username: nblanchet
  password:
